# Generated by Django 5.0.1 on 2024-02-21 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invocador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_invocador', models.CharField(blank=True, max_length=50)),
                ('tag', models.CharField(blank=True, max_length=10)),
                ('profile_icon', models.CharField(blank=True, max_length=10)),
                ('puuid', models.CharField(blank=True, max_length=100)),
                ('summonerId', models.CharField(blank=True, max_length=100)),
                ('level', models.IntegerField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ranks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soloqueue_tier', models.CharField(blank=True, max_length=20)),
                ('soloqueue_rank', models.CharField(blank=True, max_length=5)),
                ('soloqueue_leaguePoints', models.IntegerField(blank=True)),
                ('soloqueue_wins', models.IntegerField(blank=True)),
                ('soloqueue_losses', models.IntegerField(blank=True)),
                ('flexqueue_tier', models.CharField(blank=True, max_length=20)),
                ('flexqueue_rank', models.CharField(blank=True, max_length=5)),
                ('flexqueue_leaguePoints', models.IntegerField(blank=True)),
                ('flexqueue_wins', models.IntegerField(blank=True)),
                ('flexqueue_losses', models.IntegerField(blank=True)),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.invocador')),
            ],
        ),
    ]
