# Generated by Django 5.0.1 on 2024-02-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invocador',
            name='profile_icon',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='invocador',
            name='puuid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
