# Generated by Django 5.0.1 on 2024-02-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invocador',
            name='summonerName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchID', models.CharField(blank=True, max_length=20)),
                ('data_json', models.TextField(blank=True)),
                ('date', models.DateTimeField(blank=True)),
                ('gameMode', models.CharField(blank=True, max_length=20)),
                ('gameVersion', models.CharField(blank=True, max_length=20)),
                ('summoner', models.ManyToManyField(related_name='+', to='home.invocador')),
            ],
        ),
    ]
