# Generated by Django 5.0.1 on 2024-05-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_invocador_summonername_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='invocador',
            name='last_updated_profile',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
