# Generated by Django 5.0.1 on 2025-02-10 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_invocador_last_updated_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('startTime', models.DateTimeField(blank=True, null=True)),
                ('actual', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='matches',
            name='season',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.season'),
        ),
    ]
