# Generated by Django 5.0.1 on 2025-02-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_season_matches_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='invocador',
            name='admin_authorized',
            field=models.BooleanField(default=False),
        ),
    ]
