# Generated by Django 5.0.1 on 2025-02-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_invocador_admin_authorized'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='gameDuration',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='matches',
            name='matchFinish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='matches',
            name='queueType',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
