version: '3.8'

services:
  mysql:
    image: mariadb:11.1.2
    command: --default-authentication-plugin=mysql_native_password --expire-logs-days=2 --local-infile=1 --innodb-buffer-pool-size=2G
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 180695
    volumes:
      - maria-data:/var/lib/mysql
    networks:
      - geolol-network
    ulimits:
      memlock: 262144

  redis:
    image: redis:7
    restart: always
    ports:
      - "6380:6379"
    networks:
      - geolol-network
    volumes:
      - redis-data:/data
    command:
      - redis-server
      - --save 60 1
      - --loglevel warning

volumes:
    maria-data:
    redis-data:

networks:
  geolol-network:
    name: geolol-network
