# Generated by Django 5.0.1 on 2024-05-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riot_admin', '0002_adminset_status_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminset',
            name='current_patch',
            field=models.CharField(default='', max_length=20),
        ),
    ]
