# Generated by Django 5.0.1 on 2025-02-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhantomRanks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summonerName', models.CharField(blank=True, max_length=50)),
                ('puuid', models.CharField(blank=True, max_length=100)),
                ('summonerId', models.CharField(blank=True, max_length=100)),
                ('profile_icon', models.CharField(blank=True, max_length=10)),
                ('soloqueue_tier', models.CharField(blank=True, max_length=20)),
                ('soloqueue_rank', models.CharField(blank=True, max_length=5)),
                ('soloqueue_leaguePoints', models.IntegerField(blank=True)),
                ('soloqueue_wins', models.IntegerField(blank=True)),
                ('soloqueue_losses', models.IntegerField(blank=True)),
                ('flexqueue_tier', models.CharField(blank=True, max_length=20)),
                ('flexqueue_rank', models.CharField(blank=True, max_length=5)),
                ('flexqueue_leaguePoints', models.IntegerField(blank=True)),
                ('flexqueue_wins', models.IntegerField(blank=True)),
                ('flexqueue_losses', models.IntegerField(blank=True)),
            ],
        ),
    ]
