# Generated by Django 5.0.1 on 2025-02-27 11:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
        ('home', '0007_summonerdatamatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('soloqueue_tier', models.CharField(blank=True, max_length=20)),
                ('soloqueue_rank', models.CharField(blank=True, max_length=5)),
                ('soloqueue_leaguePoints', models.IntegerField(blank=True)),
                ('soloqueue_wins', models.IntegerField(blank=True)),
                ('soloqueue_losses', models.IntegerField(blank=True)),
                ('flexqueue_tier', models.CharField(blank=True, max_length=20)),
                ('flexqueue_rank', models.CharField(blank=True, max_length=5)),
                ('flexqueue_leaguePoints', models.IntegerField(blank=True)),
                ('flexqueue_wins', models.IntegerField(blank=True)),
                ('flexqueue_losses', models.IntegerField(blank=True)),
                ('season', models.ForeignKey(default=datetime.datetime(2025, 2, 27, 0, 0), null=True, on_delete=django.db.models.deletion.CASCADE, to='home.season')),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_rank', to='home.invocador')),
            ],
        ),
    ]
