# Generated by Django 5.0.1 on 2025-03-01 18:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_diaryrank'),
        ('home', '0007_summonerdatamatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryrank',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diaryrank',
            name='season',
            field=models.ForeignKey(default=datetime.datetime(2025, 3, 1, 0, 0), null=True, on_delete=django.db.models.deletion.CASCADE, to='home.season'),
        ),
    ]
